{{ range $fahcount, $e := until (.Values.foldingReplicaCount|int) -}}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $.Values.name }}-{{ $fahcount }}
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/affinity: cookie
    external-dns.alpha.kubernetes.io/target: {{ $.Values.foldingDNStarget }}
spec:
  rules:
  - host: fah-{{ $fahcount }}.{{ $.Values.foldingDomain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $.Values.name }}-{{ $fahcount }}
          servicePort: 80
{{ end -}}
