apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
  labels:
    app.kubernetes.io/managed-by: {{ .Values.name }}
data:
  passkey: {{ default "" .Values.folding.passkey | b64enc | quote }}
