apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  serviceName: "{{ .Values.name }}"
  replicas: {{ .Values.foldingReplicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
        - name: data-volume
          emptyDir: {}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          image: "{{ .Values.image.repository }}:{{ .Values.image.version }}"
          imagePullPolicy: Always
          env:
            - name: USER
              value: "{{ .Values.folding.user }}"
            - name: TEAM
              value: "{{ .Values.folding.team }}"
            - name: PASSKEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}
                  key: {{ .Values.folding.passkey }}
                  optional: true
            - name: POWER
              value: "{{ .Values.folding.power }}"
          volumeMounts:
            - mountPath: /home/folding
              name: data-volume
          ports:
            - name: http
              containerPort: 7396
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /favicon.ico
              port: 7396
          resources: {}
